#!/bin/sh

docker stop intra-notifs
docker rm intra-notifs
docker rmi intra-notifs:python

docker build -t intra-notifs:python .

docker run --restart=always -d --name intra-notifs intra-notifs:python
docker logs -f intra-notifs
